{"state": {"1": {"internet": {"status": "up", "time": "2021-02-26 14:46:43"}}}, "alerts": {"1": {"id": "6a3852b8-77fa-474b-8fd5-61d879493464", "key": "SensorStatusChanged(sensorId: 8, status: \"overUpperAlertBound\")", "time": "2021-02-26T15:38:45.797696", "type": "SensorStatusChanged", "severity": 2, "properties": "{\"sensorName\":\"moisture\",\"status\":\"overUpperAlertBound\",\"measuredValue\":100}"}, "2": {"id": "986439dd-261b-4e68-bcd9-6045fb39c70b", "key": "IrrigationRunFailed(2021-03-02 11:11:37\")", "time": "2021-03-02T11:11:37.699679", "type": "IrrigationRunFailed", "severity": 2, "properties": "{\"stacktrace\":\"Traceback (most recent call last):\n  File \"c:\\Workspace\\SzatmarTech\\Cultiva\\Cultiva.Node\\app\\irrigation\\module.py\", line 373, in run_irrigation_programme\n    raise Exception('Could not connect to irrigation controller')\nException: Could not connect to irrigation controller\n\" }"}}}